#include "vmlinux.h"
#include <bpf/bpf_helpers.h>
#include <bpf/bpf_tracing.h>
#include <bpf/bpf_core_read.h>
#include "monitor3.h"

struct {
    __uint(type, BPF_MAP_TYPE_PERF_EVENT_ARRAY);
    __uint(key_size, sizeof(u32));
    __uint(value_size, sizeof(u32));
} output SEC(".maps");

struct kernel_tracepoints {
	unsigned short common_type;
    unsigned char common_flags;
    unsigned char common_preempt_count;
    int common_pid;

	long syscall_nr;
	void *filename_ptr;
	long argv_ptr;
	long envp_ptr;
};

#define TRACE_SYSCALL(syscall_name, tp_name) \
int trace_##syscall_name(struct kernel_tracepoints *ctx) { \
    struct data_t data = {}; \
    data.pid = bpf_get_current_pid_tgid() >> 32; \
    data.uid = bpf_get_current_uid_gid() & 0xFFFFFFFF; \
    bpf_get_current_comm(&data.command, sizeof(data.command)); \
    bpf_probe_read_kernel(&data.syscall, sizeof(data.syscall), tp_name); \
    if (data.uid >= 0) { \
        bpf_perf_event_output(ctx, &output, BPF_F_CURRENT_CPU, &data, sizeof(data)); \
    } \
    return 0; \
}

SEC("tp/syscalls/sys_enter_llistxattr")
TRACE_SYSCALL(sys_enter_llistxattr, "sys_enter_llistxattr")
SEC("tp/syscalls/sys_enter_setgroups")
TRACE_SYSCALL(sys_enter_setgroups, "sys_enter_setgroups")
SEC("tp/syscalls/sys_enter_lremovexattr")
TRACE_SYSCALL(sys_enter_lremovexattr, "sys_enter_lremovexattr")
SEC("tp/syscalls/sys_enter_sethostname")
TRACE_SYSCALL(sys_enter_sethostname, "sys_enter_sethostname")
SEC("tp/syscalls/sys_enter_accept")
TRACE_SYSCALL(sys_enter_accept, "sys_enter_accept")
SEC("tp/syscalls/sys_enter_lseek")
TRACE_SYSCALL(sys_enter_lseek, "sys_enter_lseek")
SEC("tp/syscalls/sys_enter_setitimer")
TRACE_SYSCALL(sys_enter_setitimer, "sys_enter_setitimer")
SEC("tp/syscalls/sys_enter_accept4")
TRACE_SYSCALL(sys_enter_accept4, "sys_enter_accept4")
SEC("tp/syscalls/sys_enter_lsetxattr")
TRACE_SYSCALL(sys_enter_lsetxattr, "sys_enter_lsetxattr")
SEC("tp/syscalls/sys_enter_setns")
TRACE_SYSCALL(sys_enter_setns, "sys_enter_setns")
SEC("tp/syscalls/sys_enter_acct")
TRACE_SYSCALL(sys_enter_acct, "sys_enter_acct")
SEC("tp/syscalls/sys_enter_madvise")
TRACE_SYSCALL(sys_enter_madvise, "sys_enter_madvise")
SEC("tp/syscalls/sys_enter_setpgid")
TRACE_SYSCALL(sys_enter_setpgid, "sys_enter_setpgid")
SEC("tp/syscalls/sys_enter_add_key")
TRACE_SYSCALL(sys_enter_add_key, "sys_enter_add_key")
SEC("tp/syscalls/sys_enter_mbind")
TRACE_SYSCALL(sys_enter_mbind, "sys_enter_mbind")
SEC("tp/syscalls/sys_enter_setpriority")
TRACE_SYSCALL(sys_enter_setpriority, "sys_enter_setpriority")
SEC("tp/syscalls/sys_enter_adjtimex")
TRACE_SYSCALL(sys_enter_adjtimex, "sys_enter_adjtimex")
SEC("tp/syscalls/sys_enter_membarrier")
TRACE_SYSCALL(sys_enter_membarrier, "sys_enter_membarrier")
SEC("tp/syscalls/sys_enter_setregid")
TRACE_SYSCALL(sys_enter_setregid, "sys_enter_setregid")
SEC("tp/syscalls/sys_enter_personality")
TRACE_SYSCALL(sys_enter_personality, "sys_enter_personality")
SEC("tp/syscalls/sys_enter_memfd_create")
TRACE_SYSCALL(sys_enter_memfd_create, "sys_enter_memfd_create")
SEC("tp/syscalls/sys_enter_setresgid")
TRACE_SYSCALL(sys_enter_setresgid, "sys_enter_setresgid")
SEC("tp/syscalls/sys_enter_bind")
TRACE_SYSCALL(sys_enter_bind, "sys_enter_bind")
SEC("tp/syscalls/sys_enter_memfd_secret")
TRACE_SYSCALL(sys_enter_memfd_secret, "sys_enter_memfd_secret")
SEC("tp/syscalls/sys_enter_setresuid")
TRACE_SYSCALL(sys_enter_setresuid, "sys_enter_setresuid")
SEC("tp/syscalls/sys_enter_bpf")
TRACE_SYSCALL(sys_enter_bpf, "sys_enter_bpf")
SEC("tp/syscalls/sys_enter_migrate_pages")
TRACE_SYSCALL(sys_enter_migrate_pages, "sys_enter_migrate_pages")
SEC("tp/syscalls/sys_enter_setreuid")
TRACE_SYSCALL(sys_enter_setreuid, "sys_enter_setreuid")
SEC("tp/syscalls/sys_enter_brk")
TRACE_SYSCALL(sys_enter_brk, "sys_enter_brk")
SEC("tp/syscalls/sys_enter_mincore")
TRACE_SYSCALL(sys_enter_mincore, "sys_enter_mincore")
SEC("tp/syscalls/sys_enter_setrlimit")
TRACE_SYSCALL(sys_enter_setrlimit, "sys_enter_setrlimit")
SEC("tp/syscalls/sys_enter_capget")
TRACE_SYSCALL(sys_enter_capget, "sys_enter_capget")
SEC("tp/syscalls/sys_enter_mkdirat")
TRACE_SYSCALL(sys_enter_mkdirat, "sys_enter_mkdirat")
SEC("tp/syscalls/sys_enter_setsid")
TRACE_SYSCALL(sys_enter_setsid, "sys_enter_setsid")
SEC("tp/syscalls/sys_enter_capset")
TRACE_SYSCALL(sys_enter_capset, "sys_enter_capset")
SEC("tp/syscalls/sys_enter_mknodat")
TRACE_SYSCALL(sys_enter_mknodat, "sys_enter_mknodat")
SEC("tp/syscalls/sys_enter_setsockopt")
TRACE_SYSCALL(sys_enter_setsockopt, "sys_enter_setsockopt")
SEC("tp/syscalls/sys_enter_chdir")
TRACE_SYSCALL(sys_enter_chdir, "sys_enter_chdir")
SEC("tp/syscalls/sys_enter_mlock")
TRACE_SYSCALL(sys_enter_mlock, "sys_enter_mlock")
SEC("tp/syscalls/sys_enter_settimeofday")
TRACE_SYSCALL(sys_enter_settimeofday, "sys_enter_settimeofday")
SEC("tp/syscalls/sys_enter_chroot")
TRACE_SYSCALL(sys_enter_chroot, "sys_enter_chroot")
SEC("tp/syscalls/sys_enter_mlock2")
TRACE_SYSCALL(sys_enter_mlock2, "sys_enter_mlock2")
SEC("tp/syscalls/sys_enter_setuid")
TRACE_SYSCALL(sys_enter_setuid, "sys_enter_setuid")
SEC("tp/syscalls/sys_enter_clock_adjtime")
TRACE_SYSCALL(sys_enter_clock_adjtime, "sys_enter_clock_adjtime")
SEC("tp/syscalls/sys_enter_mlockall")
TRACE_SYSCALL(sys_enter_mlockall, "sys_enter_mlockall")
SEC("tp/syscalls/sys_enter_setxattr")
TRACE_SYSCALL(sys_enter_setxattr, "sys_enter_setxattr")
SEC("tp/syscalls/sys_enter_clock_getres")
TRACE_SYSCALL(sys_enter_clock_getres, "sys_enter_clock_getres")
SEC("tp/syscalls/sys_enter_mmap")
TRACE_SYSCALL(sys_enter_mmap, "sys_enter_mmap")
SEC("tp/syscalls/sys_enter_shmat")
TRACE_SYSCALL(sys_enter_shmat, "sys_enter_shmat")
SEC("tp/syscalls/sys_enter_clock_gettime")
TRACE_SYSCALL(sys_enter_clock_gettime, "sys_enter_clock_gettime")
SEC("tp/syscalls/sys_enter_mount")
TRACE_SYSCALL(sys_enter_mount, "sys_enter_mount")
SEC("tp/syscalls/sys_enter_shmctl")
TRACE_SYSCALL(sys_enter_shmctl, "sys_enter_shmctl")
SEC("tp/syscalls/sys_enter_clock_nanosleep")
TRACE_SYSCALL(sys_enter_clock_nanosleep, "sys_enter_clock_nanosleep")
SEC("tp/syscalls/sys_enter_mount_setattr")
TRACE_SYSCALL(sys_enter_mount_setattr, "sys_enter_mount_setattr")
SEC("tp/syscalls/sys_enter_shmdt")
TRACE_SYSCALL(sys_enter_shmdt, "sys_enter_shmdt")
SEC("tp/syscalls/sys_enter_clock_settime")
TRACE_SYSCALL(sys_enter_clock_settime, "sys_enter_clock_settime")
SEC("tp/syscalls/sys_enter_move_mount")
TRACE_SYSCALL(sys_enter_move_mount, "sys_enter_move_mount")
SEC("tp/syscalls/sys_enter_shmget")
TRACE_SYSCALL(sys_enter_shmget, "sys_enter_shmget")
SEC("tp/syscalls/sys_enter_clone")
TRACE_SYSCALL(sys_enter_clone, "sys_enter_clone")
SEC("tp/syscalls/sys_enter_move_pages")
TRACE_SYSCALL(sys_enter_move_pages, "sys_enter_move_pages")
SEC("tp/syscalls/sys_enter_shutdown")
TRACE_SYSCALL(sys_enter_shutdown, "sys_enter_shutdown")
SEC("tp/syscalls/sys_enter_clone3")
TRACE_SYSCALL(sys_enter_clone3, "sys_enter_clone3")
SEC("tp/syscalls/sys_enter_mprotect")
TRACE_SYSCALL(sys_enter_mprotect, "sys_enter_mprotect")
SEC("tp/syscalls/sys_enter_sigaltstack")
TRACE_SYSCALL(sys_enter_sigaltstack, "sys_enter_sigaltstack")
SEC("tp/syscalls/sys_enter_close")
TRACE_SYSCALL(sys_enter_close, "sys_enter_close")
SEC("tp/syscalls/sys_enter_mq_getsetattr")
TRACE_SYSCALL(sys_enter_mq_getsetattr, "sys_enter_mq_getsetattr")
SEC("tp/syscalls/sys_enter_signalfd4")
TRACE_SYSCALL(sys_enter_signalfd4, "sys_enter_signalfd4")
SEC("tp/syscalls/sys_enter_close_range")
TRACE_SYSCALL(sys_enter_close_range, "sys_enter_close_range")
SEC("tp/syscalls/sys_enter_mq_notify")
TRACE_SYSCALL(sys_enter_mq_notify, "sys_enter_mq_notify")
SEC("tp/syscalls/sys_enter_socket")
TRACE_SYSCALL(sys_enter_socket, "sys_enter_socket")
SEC("tp/syscalls/sys_enter_connect")
TRACE_SYSCALL(sys_enter_connect, "sys_enter_connect")
SEC("tp/syscalls/sys_enter_mq_open")
TRACE_SYSCALL(sys_enter_mq_open, "sys_enter_mq_open")
SEC("tp/syscalls/sys_enter_socketpair")
TRACE_SYSCALL(sys_enter_socketpair, "sys_enter_socketpair")
SEC("tp/syscalls/sys_enter_copy_file_range")
TRACE_SYSCALL(sys_enter_copy_file_range, "sys_enter_copy_file_range")
SEC("tp/syscalls/sys_enter_mq_timedreceive")
TRACE_SYSCALL(sys_enter_mq_timedreceive, "sys_enter_mq_timedreceive")
SEC("tp/syscalls/sys_enter_splice")
TRACE_SYSCALL(sys_enter_splice, "sys_enter_splice")
SEC("tp/syscalls/sys_enter_delete_module")
TRACE_SYSCALL(sys_enter_delete_module, "sys_enter_delete_module")
SEC("tp/syscalls/sys_enter_mq_timedsend")
TRACE_SYSCALL(sys_enter_mq_timedsend, "sys_enter_mq_timedsend")
SEC("tp/syscalls/sys_enter_statfs")
TRACE_SYSCALL(sys_enter_statfs, "sys_enter_statfs")
SEC("tp/syscalls/sys_enter_dup")
TRACE_SYSCALL(sys_enter_dup, "sys_enter_dup")
SEC("tp/syscalls/sys_enter_mq_unlink")
TRACE_SYSCALL(sys_enter_mq_unlink, "sys_enter_mq_unlink")
SEC("tp/syscalls/sys_enter_statx")
TRACE_SYSCALL(sys_enter_statx, "sys_enter_statx")
SEC("tp/syscalls/sys_enter_dup3")
TRACE_SYSCALL(sys_enter_dup3, "sys_enter_dup3")
SEC("tp/syscalls/sys_enter_mremap")
TRACE_SYSCALL(sys_enter_mremap, "sys_enter_mremap")
SEC("tp/syscalls/sys_enter_swapoff")
TRACE_SYSCALL(sys_enter_swapoff, "sys_enter_swapoff")
SEC("tp/syscalls/sys_enter_epoll_create1")
TRACE_SYSCALL(sys_enter_epoll_create1, "sys_enter_epoll_create1")
SEC("tp/syscalls/sys_enter_msgctl")
TRACE_SYSCALL(sys_enter_msgctl, "sys_enter_msgctl")
SEC("tp/syscalls/sys_enter_swapon")
TRACE_SYSCALL(sys_enter_swapon, "sys_enter_swapon")
SEC("tp/syscalls/sys_enter_epoll_ctl")
TRACE_SYSCALL(sys_enter_epoll_ctl, "sys_enter_epoll_ctl")
SEC("tp/syscalls/sys_enter_msgget")
TRACE_SYSCALL(sys_enter_msgget, "sys_enter_msgget")
SEC("tp/syscalls/sys_enter_symlinkat")
TRACE_SYSCALL(sys_enter_symlinkat, "sys_enter_symlinkat")
SEC("tp/syscalls/sys_enter_epoll_pwait")
TRACE_SYSCALL(sys_enter_epoll_pwait, "sys_enter_epoll_pwait")
SEC("tp/syscalls/sys_enter_msgrcv")
TRACE_SYSCALL(sys_enter_msgrcv, "sys_enter_msgrcv")
SEC("tp/syscalls/sys_enter_sync")
TRACE_SYSCALL(sys_enter_sync, "sys_enter_sync")
SEC("tp/syscalls/sys_enter_epoll_pwait2")
TRACE_SYSCALL(sys_enter_epoll_pwait2, "sys_enter_epoll_pwait2")
SEC("tp/syscalls/sys_enter_msgsnd")
TRACE_SYSCALL(sys_enter_msgsnd, "sys_enter_msgsnd")
SEC("tp/syscalls/sys_enter_sync_file_range")
TRACE_SYSCALL(sys_enter_sync_file_range, "sys_enter_sync_file_range")
SEC("tp/syscalls/sys_enter_eventfd2")
TRACE_SYSCALL(sys_enter_eventfd2, "sys_enter_eventfd2")
SEC("tp/syscalls/sys_enter_msync")
TRACE_SYSCALL(sys_enter_msync, "sys_enter_msync")
SEC("tp/syscalls/sys_enter_syncfs")
TRACE_SYSCALL(sys_enter_syncfs, "sys_enter_syncfs")
SEC("tp/syscalls/sys_enter_execve")
TRACE_SYSCALL(sys_enter_execve, "sys_enter_execve")
SEC("tp/syscalls/sys_enter_munlock")
TRACE_SYSCALL(sys_enter_munlock, "sys_enter_munlock")
SEC("tp/syscalls/sys_enter_sysinfo")
TRACE_SYSCALL(sys_enter_sysinfo, "sys_enter_sysinfo")
SEC("tp/syscalls/sys_enter_execveat")
TRACE_SYSCALL(sys_enter_execveat, "sys_enter_execveat")
SEC("tp/syscalls/sys_enter_munlockall")
TRACE_SYSCALL(sys_enter_munlockall, "sys_enter_munlockall")
SEC("tp/syscalls/sys_enter_syslog")
TRACE_SYSCALL(sys_enter_syslog, "sys_enter_syslog")
SEC("tp/syscalls/sys_enter_exit")
TRACE_SYSCALL(sys_enter_exit, "sys_enter_exit")
SEC("tp/syscalls/sys_enter_munmap")
TRACE_SYSCALL(sys_enter_munmap, "sys_enter_munmap")
SEC("tp/syscalls/sys_enter_tee")
TRACE_SYSCALL(sys_enter_tee, "sys_enter_tee")
SEC("tp/syscalls/sys_enter_exit_group")
TRACE_SYSCALL(sys_enter_exit_group, "sys_enter_exit_group")
SEC("tp/syscalls/sys_enter_name_to_handle_at")
TRACE_SYSCALL(sys_enter_name_to_handle_at, "sys_enter_name_to_handle_at")
SEC("tp/syscalls/sys_enter_tgkill")
TRACE_SYSCALL(sys_enter_tgkill, "sys_enter_tgkill")
SEC("tp/syscalls/sys_enter_faccessat")
TRACE_SYSCALL(sys_enter_faccessat, "sys_enter_faccessat")
SEC("tp/syscalls/sys_enter_nanosleep")
TRACE_SYSCALL(sys_enter_nanosleep, "sys_enter_nanosleep")
SEC("tp/syscalls/sys_enter_timer_create")
TRACE_SYSCALL(sys_enter_timer_create, "sys_enter_timer_create")
SEC("tp/syscalls/sys_enter_faccessat2")
TRACE_SYSCALL(sys_enter_faccessat2, "sys_enter_faccessat2")
SEC("tp/syscalls/sys_enter_newfstat")
TRACE_SYSCALL(sys_enter_newfstat, "sys_enter_newfstat")
SEC("tp/syscalls/sys_enter_timer_delete")
TRACE_SYSCALL(sys_enter_timer_delete, "sys_enter_timer_delete")
SEC("tp/syscalls/sys_enter_fadvise64")
TRACE_SYSCALL(sys_enter_fadvise64, "sys_enter_fadvise64")
SEC("tp/syscalls/sys_enter_newfstatat")
TRACE_SYSCALL(sys_enter_newfstatat, "sys_enter_newfstatat")
SEC("tp/syscalls/sys_enter_timer_getoverrun")
TRACE_SYSCALL(sys_enter_timer_getoverrun, "sys_enter_timer_getoverrun")
SEC("tp/syscalls/sys_enter_fallocate")
TRACE_SYSCALL(sys_enter_fallocate, "sys_enter_fallocate")
SEC("tp/syscalls/sys_enter_newuname")
TRACE_SYSCALL(sys_enter_newuname, "sys_enter_newuname")
SEC("tp/syscalls/sys_enter_timer_gettime")
TRACE_SYSCALL(sys_enter_timer_gettime, "sys_enter_timer_gettime")
SEC("tp/syscalls/sys_enter_fanotify_init")
TRACE_SYSCALL(sys_enter_fanotify_init, "sys_enter_fanotify_init")
SEC("tp/syscalls/sys_enter_open_by_handle_at")
TRACE_SYSCALL(sys_enter_open_by_handle_at, "sys_enter_open_by_handle_at")
SEC("tp/syscalls/sys_enter_timer_settime")
TRACE_SYSCALL(sys_enter_timer_settime, "sys_enter_timer_settime")
SEC("tp/syscalls/sys_enter_fanotify_mark")
TRACE_SYSCALL(sys_enter_fanotify_mark, "sys_enter_fanotify_mark")
SEC("tp/syscalls/sys_enter_open_tree")
TRACE_SYSCALL(sys_enter_open_tree, "sys_enter_open_tree")
SEC("tp/syscalls/sys_enter_timerfd_create")
TRACE_SYSCALL(sys_enter_timerfd_create, "sys_enter_timerfd_create")
SEC("tp/syscalls/sys_enter_fchdir")
TRACE_SYSCALL(sys_enter_fchdir, "sys_enter_fchdir")
SEC("tp/syscalls/sys_enter_openat")
TRACE_SYSCALL(sys_enter_openat, "sys_enter_openat")
SEC("tp/syscalls/sys_enter_timerfd_gettime")
TRACE_SYSCALL(sys_enter_timerfd_gettime, "sys_enter_timerfd_gettime")
SEC("tp/syscalls/sys_enter_fchmod")
TRACE_SYSCALL(sys_enter_fchmod, "sys_enter_fchmod")
SEC("tp/syscalls/sys_enter_openat2")
TRACE_SYSCALL(sys_enter_openat2, "sys_enter_openat2")
SEC("tp/syscalls/sys_enter_timerfd_settime")
TRACE_SYSCALL(sys_enter_timerfd_settime, "sys_enter_timerfd_settime")
SEC("tp/syscalls/sys_enter_fchmodat")
TRACE_SYSCALL(sys_enter_fchmodat, "sys_enter_fchmodat")
SEC("tp/syscalls/sys_enter_perf_event_open")
TRACE_SYSCALL(sys_enter_perf_event_open, "sys_enter_perf_event_open")
SEC("tp/syscalls/sys_enter_times")
TRACE_SYSCALL(sys_enter_times, "sys_enter_times")
SEC("tp/syscalls/sys_enter_fchown")
TRACE_SYSCALL(sys_enter_fchown, "sys_enter_fchown")
SEC("tp/syscalls/sys_enter_pidfd_getfd")
TRACE_SYSCALL(sys_enter_pidfd_getfd, "sys_enter_pidfd_getfd")
SEC("tp/syscalls/sys_enter_tkill")
TRACE_SYSCALL(sys_enter_tkill, "sys_enter_tkill")
SEC("tp/syscalls/sys_enter_fchownat")
TRACE_SYSCALL(sys_enter_fchownat, "sys_enter_fchownat")
SEC("tp/syscalls/sys_enter_pidfd_open")
TRACE_SYSCALL(sys_enter_pidfd_open, "sys_enter_pidfd_open")
SEC("tp/syscalls/sys_enter_truncate")
TRACE_SYSCALL(sys_enter_truncate, "sys_enter_truncate")
SEC("tp/syscalls/sys_enter_fcntl")
TRACE_SYSCALL(sys_enter_fcntl, "sys_enter_fcntl")
SEC("tp/syscalls/sys_enter_pidfd_send_signal")
TRACE_SYSCALL(sys_enter_pidfd_send_signal, "sys_enter_pidfd_send_signal")
SEC("tp/syscalls/sys_enter_umask")
TRACE_SYSCALL(sys_enter_umask, "sys_enter_umask")
SEC("tp/syscalls/sys_enter_fdatasync")
TRACE_SYSCALL(sys_enter_fdatasync, "sys_enter_fdatasync")
SEC("tp/syscalls/sys_enter_pipe2")
TRACE_SYSCALL(sys_enter_pipe2, "sys_enter_pipe2")
SEC("tp/syscalls/sys_enter_umount")
TRACE_SYSCALL(sys_enter_umount, "sys_enter_umount")
SEC("tp/syscalls/sys_enter_fgetxattr")
TRACE_SYSCALL(sys_enter_fgetxattr, "sys_enter_fgetxattr")
SEC("tp/syscalls/sys_enter_pivot_root")
TRACE_SYSCALL(sys_enter_pivot_root, "sys_enter_pivot_root")
SEC("tp/syscalls/sys_enter_unlinkat")
TRACE_SYSCALL(sys_enter_unlinkat, "sys_enter_unlinkat")
SEC("tp/syscalls/sys_enter_finit_module")
TRACE_SYSCALL(sys_enter_finit_module, "sys_enter_finit_module")
SEC("tp/syscalls/sys_enter_ppoll")
TRACE_SYSCALL(sys_enter_ppoll, "sys_enter_ppoll")
SEC("tp/syscalls/sys_enter_unshare")
TRACE_SYSCALL(sys_enter_unshare, "sys_enter_unshare")
SEC("tp/syscalls/sys_enter_flistxattr")
TRACE_SYSCALL(sys_enter_flistxattr, "sys_enter_flistxattr")
SEC("tp/syscalls/sys_enter_prctl")
TRACE_SYSCALL(sys_enter_prctl, "sys_enter_prctl")
SEC("tp/syscalls/sys_enter_userfaultfd")
TRACE_SYSCALL(sys_enter_userfaultfd, "sys_enter_userfaultfd")
SEC("tp/syscalls/sys_enter_flock")
TRACE_SYSCALL(sys_enter_flock, "sys_enter_flock")
SEC("tp/syscalls/sys_enter_pread64")
TRACE_SYSCALL(sys_enter_pread64, "sys_enter_pread64")
SEC("tp/syscalls/sys_enter_utimensat")
TRACE_SYSCALL(sys_enter_utimensat, "sys_enter_utimensat")
SEC("tp/syscalls/sys_enter_fremovexattr")
TRACE_SYSCALL(sys_enter_fremovexattr, "sys_enter_fremovexattr")
SEC("tp/syscalls/sys_enter_preadv")
TRACE_SYSCALL(sys_enter_preadv, "sys_enter_preadv")
SEC("tp/syscalls/sys_enter_vhangup")
TRACE_SYSCALL(sys_enter_vhangup, "sys_enter_vhangup")
SEC("tp/syscalls/sys_enter_fsconfig")
TRACE_SYSCALL(sys_enter_fsconfig, "sys_enter_fsconfig")
SEC("tp/syscalls/sys_enter_preadv2")
TRACE_SYSCALL(sys_enter_preadv2, "sys_enter_preadv2")
SEC("tp/syscalls/sys_enter_vmsplice")
TRACE_SYSCALL(sys_enter_vmsplice, "sys_enter_vmsplice")
SEC("tp/syscalls/sys_enter_fsetxattr")
TRACE_SYSCALL(sys_enter_fsetxattr, "sys_enter_fsetxattr")
SEC("tp/syscalls/sys_enter_prlimit64")
TRACE_SYSCALL(sys_enter_prlimit64, "sys_enter_prlimit64")
SEC("tp/syscalls/sys_enter_wait4")
TRACE_SYSCALL(sys_enter_wait4, "sys_enter_wait4")
SEC("tp/syscalls/sys_enter_fsmount")
TRACE_SYSCALL(sys_enter_fsmount, "sys_enter_fsmount")
SEC("tp/syscalls/sys_enter_process_madvise")
TRACE_SYSCALL(sys_enter_process_madvise, "sys_enter_process_madvise")
SEC("tp/syscalls/sys_enter_waitid")
TRACE_SYSCALL(sys_enter_waitid, "sys_enter_waitid")
SEC("tp/syscalls/sys_enter_fsopen")
TRACE_SYSCALL(sys_enter_fsopen, "sys_enter_fsopen")
SEC("tp/syscalls/sys_enter_process_mrelease")
TRACE_SYSCALL(sys_enter_process_mrelease, "sys_enter_process_mrelease")
SEC("tp/syscalls/sys_enter_write")
TRACE_SYSCALL(sys_enter_write, "sys_enter_write")
SEC("tp/syscalls/sys_enter_fspick")
TRACE_SYSCALL(sys_enter_fspick, "sys_enter_fspick")
SEC("tp/syscalls/sys_enter_process_vm_readv")
TRACE_SYSCALL(sys_enter_process_vm_readv, "sys_enter_process_vm_readv")
SEC("tp/syscalls/sys_enter_writev")
TRACE_SYSCALL(sys_enter_writev, "sys_enter_writev")
SEC("tp/syscalls/sys_enter_fstatfs")
TRACE_SYSCALL(sys_enter_fstatfs, "sys_enter_fstatfs")
SEC("tp/syscalls/sys_enter_process_vm_writev")
TRACE_SYSCALL(sys_enter_process_vm_writev, "sys_enter_process_vm_writev")
SEC("tp/syscalls/sys_enter_fsync")
TRACE_SYSCALL(sys_enter_fsync, "sys_enter_fsync")
SEC("tp/syscalls/sys_enter_pselect6")
TRACE_SYSCALL(sys_enter_pselect6, "sys_enter_pselect6")
SEC("tp/syscalls/sys_enter_ftruncate")
TRACE_SYSCALL(sys_enter_ftruncate, "sys_enter_ftruncate")
SEC("tp/syscalls/sys_enter_ptrace")
TRACE_SYSCALL(sys_enter_ptrace, "sys_enter_ptrace")
SEC("tp/syscalls/sys_enter_futex")
TRACE_SYSCALL(sys_enter_futex, "sys_enter_futex")
SEC("tp/syscalls/sys_enter_pwrite64")
TRACE_SYSCALL(sys_enter_pwrite64, "sys_enter_pwrite64")
SEC("tp/syscalls/sys_enter_get_mempolicy")
TRACE_SYSCALL(sys_enter_get_mempolicy, "sys_enter_get_mempolicy")
SEC("tp/syscalls/sys_enter_pwritev")
TRACE_SYSCALL(sys_enter_pwritev, "sys_enter_pwritev")
SEC("tp/syscalls/sys_enter_get_robust_list")
TRACE_SYSCALL(sys_enter_get_robust_list, "sys_enter_get_robust_list")
SEC("tp/syscalls/sys_enter_pwritev2")
TRACE_SYSCALL(sys_enter_pwritev2, "sys_enter_pwritev2")
SEC("tp/syscalls/sys_enter_getcpu")
TRACE_SYSCALL(sys_enter_getcpu, "sys_enter_getcpu")
SEC("tp/syscalls/sys_enter_quotactl")
TRACE_SYSCALL(sys_enter_quotactl, "sys_enter_quotactl")
SEC("tp/syscalls/sys_enter_getcwd")
TRACE_SYSCALL(sys_enter_getcwd, "sys_enter_getcwd")
SEC("tp/syscalls/sys_enter_quotactl_fd")
TRACE_SYSCALL(sys_enter_quotactl_fd, "sys_enter_quotactl_fd")
SEC("tp/syscalls/sys_enter_getdents64")
TRACE_SYSCALL(sys_enter_getdents64, "sys_enter_getdents64")
SEC("tp/syscalls/sys_enter_read")
TRACE_SYSCALL(sys_enter_read, "sys_enter_read")
SEC("tp/syscalls/sys_enter_getegid")
TRACE_SYSCALL(sys_enter_getegid, "sys_enter_getegid")
SEC("tp/syscalls/sys_enter_readahead")
TRACE_SYSCALL(sys_enter_readahead, "sys_enter_readahead")
SEC("tp/syscalls/sys_enter_geteuid")
TRACE_SYSCALL(sys_enter_geteuid, "sys_enter_geteuid")
SEC("tp/syscalls/sys_enter_readlinkat")
TRACE_SYSCALL(sys_enter_readlinkat, "sys_enter_readlinkat")
SEC("tp/syscalls/sys_enter_getgid")
TRACE_SYSCALL(sys_enter_getgid, "sys_enter_getgid")
SEC("tp/syscalls/sys_enter_readv")
TRACE_SYSCALL(sys_enter_readv, "sys_enter_readv")
SEC("tp/syscalls/sys_enter_getgroups")
TRACE_SYSCALL(sys_enter_getgroups, "sys_enter_getgroups")
SEC("tp/syscalls/sys_enter_reboot")
TRACE_SYSCALL(sys_enter_reboot, "sys_enter_reboot")
SEC("tp/syscalls/sys_enter_getitimer")
TRACE_SYSCALL(sys_enter_getitimer, "sys_enter_getitimer")
SEC("tp/syscalls/sys_enter_recvfrom")
TRACE_SYSCALL(sys_enter_recvfrom, "sys_enter_recvfrom")
SEC("tp/syscalls/sys_enter_getpeername")
TRACE_SYSCALL(sys_enter_getpeername, "sys_enter_getpeername")
SEC("tp/syscalls/sys_enter_recvmmsg")
TRACE_SYSCALL(sys_enter_recvmmsg, "sys_enter_recvmmsg")
SEC("tp/syscalls/sys_enter_getpgid")
TRACE_SYSCALL(sys_enter_getpgid, "sys_enter_getpgid")
SEC("tp/syscalls/sys_enter_recvmsg")
TRACE_SYSCALL(sys_enter_recvmsg, "sys_enter_recvmsg")
SEC("tp/syscalls/sys_enter_getpid")
TRACE_SYSCALL(sys_enter_getpid, "sys_enter_getpid")
SEC("tp/syscalls/sys_enter_remap_file_pages")
TRACE_SYSCALL(sys_enter_remap_file_pages, "sys_enter_remap_file_pages")
SEC("tp/syscalls/sys_enter_getppid")
TRACE_SYSCALL(sys_enter_getppid, "sys_enter_getppid")
SEC("tp/syscalls/sys_enter_removexattr")
TRACE_SYSCALL(sys_enter_removexattr, "sys_enter_removexattr")
SEC("tp/syscalls/sys_enter_getpriority")
TRACE_SYSCALL(sys_enter_getpriority, "sys_enter_getpriority")
SEC("tp/syscalls/sys_enter_renameat")
TRACE_SYSCALL(sys_enter_renameat, "sys_enter_renameat")
SEC("tp/syscalls/sys_enter_getrandom")
TRACE_SYSCALL(sys_enter_getrandom, "sys_enter_getrandom")
SEC("tp/syscalls/sys_enter_renameat2")
TRACE_SYSCALL(sys_enter_renameat2, "sys_enter_renameat2")
SEC("tp/syscalls/sys_enter_getresgid")
TRACE_SYSCALL(sys_enter_getresgid, "sys_enter_getresgid")
SEC("tp/syscalls/sys_enter_request_key")
TRACE_SYSCALL(sys_enter_request_key, "sys_enter_request_key")
SEC("tp/syscalls/sys_enter_getresuid")
TRACE_SYSCALL(sys_enter_getresuid, "sys_enter_getresuid")
SEC("tp/syscalls/sys_enter_restart_syscall")
TRACE_SYSCALL(sys_enter_restart_syscall, "sys_enter_restart_syscall")
SEC("tp/syscalls/sys_enter_getrlimit")
TRACE_SYSCALL(sys_enter_getrlimit, "sys_enter_getrlimit")
SEC("tp/syscalls/sys_enter_rseq")
TRACE_SYSCALL(sys_enter_rseq, "sys_enter_rseq")
SEC("tp/syscalls/sys_enter_getrusage")
TRACE_SYSCALL(sys_enter_getrusage, "sys_enter_getrusage")
SEC("tp/syscalls/sys_enter_rt_sigaction")
TRACE_SYSCALL(sys_enter_rt_sigaction, "sys_enter_rt_sigaction")
SEC("tp/syscalls/sys_enter_getsid")
TRACE_SYSCALL(sys_enter_getsid, "sys_enter_getsid")
SEC("tp/syscalls/sys_enter_rt_sigpending")
TRACE_SYSCALL(sys_enter_rt_sigpending, "sys_enter_rt_sigpending")
SEC("tp/syscalls/sys_enter_getsockname")
TRACE_SYSCALL(sys_enter_getsockname, "sys_enter_getsockname")
SEC("tp/syscalls/sys_enter_rt_sigprocmask")
TRACE_SYSCALL(sys_enter_rt_sigprocmask, "sys_enter_rt_sigprocmask")
SEC("tp/syscalls/sys_enter_getsockopt")
TRACE_SYSCALL(sys_enter_getsockopt, "sys_enter_getsockopt")
SEC("tp/syscalls/sys_enter_rt_sigqueueinfo")
TRACE_SYSCALL(sys_enter_rt_sigqueueinfo, "sys_enter_rt_sigqueueinfo")
SEC("tp/syscalls/sys_enter_gettid")
TRACE_SYSCALL(sys_enter_gettid, "sys_enter_gettid")
SEC("tp/syscalls/sys_enter_rt_sigreturn")
TRACE_SYSCALL(sys_enter_rt_sigreturn, "sys_enter_rt_sigreturn")
SEC("tp/syscalls/sys_enter_gettimeofday")
TRACE_SYSCALL(sys_enter_gettimeofday, "sys_enter_gettimeofday")
SEC("tp/syscalls/sys_enter_rt_sigsuspend")
TRACE_SYSCALL(sys_enter_rt_sigsuspend, "sys_enter_rt_sigsuspend")
SEC("tp/syscalls/sys_enter_getuid")
TRACE_SYSCALL(sys_enter_getuid, "sys_enter_getuid")
SEC("tp/syscalls/sys_enter_rt_sigtimedwait")
TRACE_SYSCALL(sys_enter_rt_sigtimedwait, "sys_enter_rt_sigtimedwait")
SEC("tp/syscalls/sys_enter_getxattr")
TRACE_SYSCALL(sys_enter_getxattr, "sys_enter_getxattr")
SEC("tp/syscalls/sys_enter_rt_tgsigqueueinfo")
TRACE_SYSCALL(sys_enter_rt_tgsigqueueinfo, "sys_enter_rt_tgsigqueueinfo")
SEC("tp/syscalls/sys_enter_init_module")
TRACE_SYSCALL(sys_enter_init_module, "sys_enter_init_module")
SEC("tp/syscalls/sys_enter_sched_get_priority_max")
TRACE_SYSCALL(sys_enter_sched_get_priority_max, "sys_enter_sched_get_priority_max")
SEC("tp/syscalls/sys_enter_inotify_add_watch")
TRACE_SYSCALL(sys_enter_inotify_add_watch, "sys_enter_inotify_add_watch")
SEC("tp/syscalls/sys_enter_sched_get_priority_min")
TRACE_SYSCALL(sys_enter_sched_get_priority_min, "sys_enter_sched_get_priority_min")
SEC("tp/syscalls/sys_enter_inotify_init1")
TRACE_SYSCALL(sys_enter_inotify_init1, "sys_enter_inotify_init1")
SEC("tp/syscalls/sys_enter_sched_getaffinity")
TRACE_SYSCALL(sys_enter_sched_getaffinity, "sys_enter_sched_getaffinity")
SEC("tp/syscalls/sys_enter_inotify_rm_watch")
TRACE_SYSCALL(sys_enter_inotify_rm_watch, "sys_enter_inotify_rm_watch")
SEC("tp/syscalls/sys_enter_sched_getattr")
TRACE_SYSCALL(sys_enter_sched_getattr, "sys_enter_sched_getattr")
SEC("tp/syscalls/sys_enter_io_cancel")
TRACE_SYSCALL(sys_enter_io_cancel, "sys_enter_io_cancel")
SEC("tp/syscalls/sys_enter_sched_getparam")
TRACE_SYSCALL(sys_enter_sched_getparam, "sys_enter_sched_getparam")
SEC("tp/syscalls/sys_enter_io_destroy")
TRACE_SYSCALL(sys_enter_io_destroy, "sys_enter_io_destroy")
SEC("tp/syscalls/sys_enter_sched_getscheduler")
TRACE_SYSCALL(sys_enter_sched_getscheduler, "sys_enter_sched_getscheduler")
SEC("tp/syscalls/sys_enter_io_getevents")
TRACE_SYSCALL(sys_enter_io_getevents, "sys_enter_io_getevents")
SEC("tp/syscalls/sys_enter_sched_rr_get_interval")
TRACE_SYSCALL(sys_enter_sched_rr_get_interval, "sys_enter_sched_rr_get_interval")
SEC("tp/syscalls/sys_enter_io_pgetevents")
TRACE_SYSCALL(sys_enter_io_pgetevents, "sys_enter_io_pgetevents")
SEC("tp/syscalls/sys_enter_sched_setaffinity")
TRACE_SYSCALL(sys_enter_sched_setaffinity, "sys_enter_sched_setaffinity")
SEC("tp/syscalls/sys_enter_io_setup")
TRACE_SYSCALL(sys_enter_io_setup, "sys_enter_io_setup")
SEC("tp/syscalls/sys_enter_sched_setattr")
TRACE_SYSCALL(sys_enter_sched_setattr, "sys_enter_sched_setattr")
SEC("tp/syscalls/sys_enter_io_submit")
TRACE_SYSCALL(sys_enter_io_submit, "sys_enter_io_submit")
SEC("tp/syscalls/sys_enter_sched_setparam")
TRACE_SYSCALL(sys_enter_sched_setparam, "sys_enter_sched_setparam")
SEC("tp/syscalls/sys_enter_io_uring_enter")
TRACE_SYSCALL(sys_enter_io_uring_enter, "sys_enter_io_uring_enter")
SEC("tp/syscalls/sys_enter_sched_setscheduler")
TRACE_SYSCALL(sys_enter_sched_setscheduler, "sys_enter_sched_setscheduler")
SEC("tp/syscalls/sys_enter_io_uring_register")
TRACE_SYSCALL(sys_enter_io_uring_register, "sys_enter_io_uring_register")
SEC("tp/syscalls/sys_enter_sched_yield")
TRACE_SYSCALL(sys_enter_sched_yield, "sys_enter_sched_yield")
SEC("tp/syscalls/sys_enter_io_uring_setup")
TRACE_SYSCALL(sys_enter_io_uring_setup, "sys_enter_io_uring_setup")
SEC("tp/syscalls/sys_enter_seccomp")
TRACE_SYSCALL(sys_enter_seccomp, "sys_enter_seccomp")
SEC("tp/syscalls/sys_enter_ioctl")
TRACE_SYSCALL(sys_enter_ioctl, "sys_enter_ioctl")
SEC("tp/syscalls/sys_enter_semctl")
TRACE_SYSCALL(sys_enter_semctl, "sys_enter_semctl")
SEC("tp/syscalls/sys_enter_ioprio_get")
TRACE_SYSCALL(sys_enter_ioprio_get, "sys_enter_ioprio_get")
SEC("tp/syscalls/sys_enter_semget")
TRACE_SYSCALL(sys_enter_semget, "sys_enter_semget")
SEC("tp/syscalls/sys_enter_ioprio_set")
TRACE_SYSCALL(sys_enter_ioprio_set, "sys_enter_ioprio_set")
SEC("tp/syscalls/sys_enter_semop")
TRACE_SYSCALL(sys_enter_semop, "sys_enter_semop")
SEC("tp/syscalls/sys_enter_kcmp")
TRACE_SYSCALL(sys_enter_kcmp, "sys_enter_kcmp")
SEC("tp/syscalls/sys_enter_semtimedop")
TRACE_SYSCALL(sys_enter_semtimedop, "sys_enter_semtimedop")
SEC("tp/syscalls/sys_enter_kexec_file_load")
TRACE_SYSCALL(sys_enter_kexec_file_load, "sys_enter_kexec_file_load")
SEC("tp/syscalls/sys_enter_sendfile64")
TRACE_SYSCALL(sys_enter_sendfile64, "sys_enter_sendfile64")
SEC("tp/syscalls/sys_enter_kexec_load")
TRACE_SYSCALL(sys_enter_kexec_load, "sys_enter_kexec_load")
SEC("tp/syscalls/sys_enter_sendmmsg")
TRACE_SYSCALL(sys_enter_sendmmsg, "sys_enter_sendmmsg")
SEC("tp/syscalls/sys_enter_keyctl")
TRACE_SYSCALL(sys_enter_keyctl, "sys_enter_keyctl")
SEC("tp/syscalls/sys_enter_sendmsg")
TRACE_SYSCALL(sys_enter_sendmsg, "sys_enter_sendmsg")
SEC("tp/syscalls/sys_enter_kill")
TRACE_SYSCALL(sys_enter_kill, "sys_enter_kill")
SEC("tp/syscalls/sys_enter_sendto")
TRACE_SYSCALL(sys_enter_sendto, "sys_enter_sendto")
SEC("tp/syscalls/sys_enter_landlock_add_rule")
TRACE_SYSCALL(sys_enter_landlock_add_rule, "sys_enter_landlock_add_rule")
SEC("tp/syscalls/sys_enter_set_mempolicy")
TRACE_SYSCALL(sys_enter_set_mempolicy, "sys_enter_set_mempolicy")
SEC("tp/syscalls/sys_enter_landlock_create_ruleset")
TRACE_SYSCALL(sys_enter_landlock_create_ruleset, "sys_enter_landlock_create_ruleset")
SEC("tp/syscalls/sys_enter_set_robust_list")
TRACE_SYSCALL(sys_enter_set_robust_list, "sys_enter_set_robust_list")
SEC("tp/syscalls/sys_enter_landlock_restrict_self")
TRACE_SYSCALL(sys_enter_landlock_restrict_self, "sys_enter_landlock_restrict_self")
SEC("tp/syscalls/sys_enter_set_tid_address")
TRACE_SYSCALL(sys_enter_set_tid_address, "sys_enter_set_tid_address")
SEC("tp/syscalls/sys_enter_lgetxattr")
TRACE_SYSCALL(sys_enter_lgetxattr, "sys_enter_lgetxattr")
SEC("tp/syscalls/sys_enter_setdomainname")
TRACE_SYSCALL(sys_enter_setdomainname, "sys_enter_setdomainname")
SEC("tp/syscalls/sys_enter_linkat")
TRACE_SYSCALL(sys_enter_linkat, "sys_enter_linkat")
SEC("tp/syscalls/sys_enter_setfsgid")
TRACE_SYSCALL(sys_enter_setfsgid, "sys_enter_setfsgid")
SEC("tp/syscalls/sys_enter_listen")
TRACE_SYSCALL(sys_enter_listen, "sys_enter_listen")
SEC("tp/syscalls/sys_enter_setfsuid")
TRACE_SYSCALL(sys_enter_setfsuid, "sys_enter_setfsuid")
SEC("tp/syscalls/sys_enter_listxattr")
TRACE_SYSCALL(sys_enter_listxattr, "sys_enter_listxattr")
SEC("tp/syscalls/sys_enter_setgid")
TRACE_SYSCALL(sys_enter_setgid, "sys_enter_setgid")

char LICENSE[] SEC("license") = "Dual BSD/GPL";